kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: java-springboot
          image: java-springboot-image:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "10m"
            limits:
              memory: "2Gi"
              cpu: "2"
---
kind: Service
apiVersion: v1
metadata:
  name: java-springboot
spec:
  ports:
    - name: http-8080
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: demo-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-springboot
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  endpoints:
  - interval: 15s
    targetPort: http-8080
    path: /actuator/prometheus
  
